### ISSUE TITLE
The README should mention that this action produces annotations

### ISSUE THREAD

**Issue by tmke8** [jakebailey/pyright-action#12]
I had been aware of this action for some time, but never bothered to use it because this

```yaml
     - uses: actions/setup-node@v3
       with:
         node-version: "18"
     - run: npm install -g pyright
     - run: pyright my_code
```
wasn't that difficult to configure, but now I've realized that your action actually produces annotations that appear in the PR! This is definitely your killer feature!
