### ISSUE TITLE
`latest-release` is not using the latest Pyright version

### ISSUE THREAD

**Issue by tylerlaprade** [jakebailey/pyright-action#133]
My local Pylance version is using `1.1.367` or higher, since it doesn't have a bug that was fixed in that version. The GitHub Action is still running `1.1.360`. The latest Pyright version from three days ago is `1.1.371`.
```
Run jakebailey/pyright-action@v2.3.1
  with:
    pylance-version: latest-release
    annotate: all
    warnings: false
    lib: false
    no-comments: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.4/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib
    AUTH0_DOMAIN: login.sandbox.condorsoftware.com
Pylance latest-release uses pyright 1.1.360
```
This also occurred on `v1.8.1`, so it was not introduced by a recent release.
