### ISSUE TITLE
Feature Request: Allow 'lastest' as a version string

### ISSUE THREAD

**Issue by Avasam** [jakebailey/pyright-action#139]
Minimal reproducer:
```yaml
jobs:
  pyright:
    steps:
      - uses: jakebailey/pyright-action@v2
        with:
          version: latest
```
Results in:
`Error: TypeError: Invalid Version: latest`

---

I know that omitting `version` uses latest, but I'd like to be able to re-use the string "latest" as extracted from a file or configured in the github action. For a simple example:
```yaml
env:
  PYRIGHT_VERSION: "latest"

jobs:
  pyright:
    steps:
      - name: Run pyright
        uses: jakebailey/pyright-action@v2
        with:
          version: ${{ env.PYRIGHT_VERSION }}
          extra-args: --threads
```

more complex example:

```yaml
jobs:
  Pyright:
    steps:
      - name: Get pyright version
        id: pyright_version
        run: |
          PYRIGHT_VERSION=$(grep '$pyrightVersion = ' 'scripts/lint.ps1' | cut -d "#" -f 1 | cut -d = -f 2 | tr -d ' ')
          echo pyright version: "${PYRIGHT_VERSION}"
          echo PYRIGHT_VERSION="${PYRIGHT_VERSION}" >> "${GITHUB_OUTPUT}"
        shell: bash
      - name: Analysing the code with Pyright
        uses: jakebailey/pyright-action@v2
        with:
          version: ${{ steps.pyright_version.outputs.PYRIGHT_VERSION }}
          working-directory: src/
          python-version: ${{ matrix.python-version }}
```

The complex example can be worked around by adding:
```bash
          if [ "$PYRIGHT_VERSION" = "'latest'" ]; then
            PYRIGHT_VERSION=
          fi
```

But the simple case doesn't have a simple fix.
