### ISSUE TITLE
`working-directory` does not work as expected

### ISSUE THREAD

**Issue by oriash93** [jakebailey/pyright-action#153]
Hello,

I have python code in two directories, for example: path1 and path2.
I am using this action with `working-directory` as follows:

```
name: CI

on:
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    strategy:
      matrix:
        path: [path1, path2]
      fail-fast: false

    defaults:
      run:
        working-directory: ${{ matrix.path}}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.10
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Black
        uses: psf/black@stable
        with:
          src: ${{ matrix.path}}
      - name: Pyright
        uses: jakebailey/pyright-action@v2
        with:
          working-directory: ${{ matrix.path}}
```

Expected behavior:
pyright runs on the code in the specified directory.

Actual behavior:
pyright runs on all python code in the repository.
